service: ms-tt-processor

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  tt-handler:
    handler: handler.processor
    events:
      - sqs:
          arn:
            Fn::Join:
              - ':'
              - - arn
                - aws
                - sqs
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - sticker-request
